spring:
  application:
    name: ms-email-service-async
  profiles:
    active: dev
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASS:admin}
    template:
      mandatory: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: brinkscalcados@gmail.com
    password: elnt avwh gchi ytrc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
